### ISSUE TITLE
MAX_ROW initialized at wrong number

### ISSUE THREAD

**Issue by Distream79** [COMP118-01-Charalambos/Lab4Part2#1]
MAX_ROW has been initiliazed at the wrong number, it should have been 6 but it is 10. This leaves room for logical errors and miscalculations. Fixing it will guarantee a more stable run with less issues.

**Comment by CharalambosH** [comment]
I will work on this and have it fixed, please also have @Distream79 look and test it

**Comment by Distream79** [comment]
After testing the program i have verified that this is resolved in @COMP118-01-Charalambos/bugmanagement

**Comment by Distream79** [comment]
After testing the program i have verified that this is resolved in @COMP118-01-Charalambos/bugmanagement
