### ISSUE TITLE
for loop false comparison 

### ISSUE THREAD

**Issue by Distream79** [COMP118-01-Charalambos/Lab4Part2#3]
In the function sumOfCols the for loop is compared falsely to maxRow instead of MAX_COL. This issue doesn't show any output errors but is an issue that could possibly be a huge problem later on. Fixing this issue will guarantee that the program will run smoothly with less errors and bugs.

**Comment by Distream79** [comment]
After testing the program i have verified that the current issue is resolved @COMP118-01-Charalambos/bugmanagement . But another issue has appeared. A typo in the function return command always returns 0.

**Comment by CharalambosH** [comment]
I will work on this and have it fixed, please also have @Distream79 look and test it

**Comment by Distream79** [comment]
After testing the program i have verified that all issues are resolved @COMP118-01-Charalambos/bugmanagement
